# Use the official Node.js image as the base image
FROM node:18.19-alpine AS build

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY build_context/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY build_context/ ./

# Build the Angular application
RUN npm run build

# Use the official Nginx image as the base image for serving the application
FROM nginx:alpine

# Copy the built Angular application from the build stage to the Nginx HTML directory
COPY --from=build /app/dist /usr/share/nginx/html

# Copy the Nginx configuration file
COPY build_context/nginx.conf /etc/nginx/nginx.conf

# Use the official Node.js image as the base image
FROM node:18.19-alpine AS build

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY build_context/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY build_context/ ./

# Build the Angular application
RUN npm run build

# Use the official Nginx image as the base image for serving the application
FROM nginx:alpine

# Copy the built Angular application from the build stage to the Nginx HTML directory
COPY --from=build /app/dist /usr/share/nginx/html

# Copy the Nginx configuration file
COPY build_context/nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 4200

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]

